# Generated by Django 5.0.1 on 2024-01-04 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.FileField(default=django.utils.timezone.now, upload_to='info/'),
            preserve_default=False,
        ),
    ]
