# Generated by Django 5.0.1 on 2024-01-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_product_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
