# Generated by Django 5.0.1 on 2024-01-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_product_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=models.FileField(blank=True, upload_to='info/'),
        ),
    ]
